-- Script para poblar datos de Colombia
-- País: Colombia
-- Departamentos: Todos los departamentos de Colombia
-- Municipios: Solo Santander y Norte de Santander

-- Limpiar datos existentes (en orden correcto por foreign keys)
DELETE FROM municipios;
DELETE FROM departamentos;
DELETE FROM paises WHERE paisNombre = 'Colombia';

-- Insertar País: Colombia
INSERT INTO paises (paisNombre, paisCodigo, paisEstado, fechaCreacion, fechaActualizacion) 
VALUES ('Colombia', 'CO', 1, NOW(), NOW())
ON DUPLICATE KEY UPDATE paisNombre = paisNombre;

-- Obtener el ID del país Colombia
SET @pais_id = (SELECT paisId FROM paises WHERE paisNombre = 'Colombia' LIMIT 1);

-- Insertar todos los departamentos de Colombia
INSERT INTO departamentos (departamentoNombre, departamentoCodigo, paisId, departamentoEstado, fechaCreacion, fechaActualizacion) VALUES
('Amazonas', '91', @pais_id, 1, NOW(), NOW()),
('Antioquia', '05', @pais_id, 1, NOW(), NOW()),
('Arauca', '81', @pais_id, 1, NOW(), NOW()),
('Atlántico', '08', @pais_id, 1, NOW(), NOW()),
('Bolívar', '13', @pais_id, 1, NOW(), NOW()),
('Boyacá', '15', @pais_id, 1, NOW(), NOW()),
('Caldas', '17', @pais_id, 1, NOW(), NOW()),
('Caquetá', '18', @pais_id, 1, NOW(), NOW()),
('Casanare', '85', @pais_id, 1, NOW(), NOW()),
('Cauca', '19', @pais_id, 1, NOW(), NOW()),
('Cesar', '20', @pais_id, 1, NOW(), NOW()),
('Chocó', '27', @pais_id, 1, NOW(), NOW()),
('Córdoba', '23', @pais_id, 1, NOW(), NOW()),
('Cundinamarca', '25', @pais_id, 1, NOW(), NOW()),
('Guainía', '94', @pais_id, 1, NOW(), NOW()),
('Guaviare', '95', @pais_id, 1, NOW(), NOW()),
('Huila', '41', @pais_id, 1, NOW(), NOW()),
('La Guajira', '44', @pais_id, 1, NOW(), NOW()),
('Magdalena', '47', @pais_id, 1, NOW(), NOW()),
('Meta', '50', @pais_id, 1, NOW(), NOW()),
('Nariño', '52', @pais_id, 1, NOW(), NOW()),
('Norte de Santander', '54', @pais_id, 1, NOW(), NOW()),
('Putumayo', '86', @pais_id, 1, NOW(), NOW()),
('Quindío', '63', @pais_id, 1, NOW(), NOW()),
('Risaralda', '66', @pais_id, 1, NOW(), NOW()),
('San Andrés y Providencia', '88', @pais_id, 1, NOW(), NOW()),
('Santander', '68', @pais_id, 1, NOW(), NOW()),
('Sucre', '70', @pais_id, 1, NOW(), NOW()),
('Tolima', '73', @pais_id, 1, NOW(), NOW()),
('Valle del Cauca', '76', @pais_id, 1, NOW(), NOW()),
('Vaupés', '97', @pais_id, 1, NOW(), NOW()),
('Vichada', '99', @pais_id, 1, NOW(), NOW());

-- Obtener los IDs de los departamentos
SET @santander_id = (SELECT departamentoId FROM departamentos WHERE departamentoNombre = 'Santander' LIMIT 1);
SET @norte_santander_id = (SELECT departamentoId FROM departamentos WHERE departamentoNombre = 'Norte de Santander' LIMIT 1);

-- Insertar municipios de Santander
INSERT INTO municipios (municipioNombre, municipioCodigo, departamentoId, municipioEstado, fechaCreacion, fechaActualizacion) VALUES
('Bucaramanga', '68001', @santander_id, 1, NOW(), NOW()),
('Puerto Wilches', '68573', @santander_id, 1, NOW(), NOW()),
('Puerto Parra', '68572', @santander_id, 1, NOW(), NOW()),
('Sabana de Torres', '68669', @santander_id, 1, NOW(), NOW()),
('Villanueva', '68861', @santander_id, 1, NOW(), NOW()),
('Zapatoca', '68895', @santander_id, 1, NOW(), NOW()),
('Valle de San José', '68867', @santander_id, 1, NOW(), NOW()),
('Vetas', '68861', @santander_id, 1, NOW(), NOW()),
('Villanueva', '68861', @santander_id, 1, NOW(), NOW()),
('Aratoca', '68051', @santander_id, 1, NOW(), NOW()),
('Barbosa', '68079', @santander_id, 1, NOW(), NOW()),
('Bolívar', '68101', @santander_id, 1, NOW(), NOW()),
('Cabrera', '68121', @santander_id, 1, NOW(), NOW()),
('California', '68132', @santander_id, 1, NOW(), NOW()),
('Capitanejo', '68147', @santander_id, 1, NOW(), NOW()),
('Carcasí', '68152', @santander_id, 1, NOW(), NOW()),
('Cepitá', '68160', @santander_id, 1, NOW(), NOW()),
('Cerrito', '68162', @santander_id, 1, NOW(), NOW()),
('Charalá', '68167', @santander_id, 1, NOW(), NOW()),
('Charta', '68169', @santander_id, 1, NOW(), NOW()),
('Chima', '68176', @santander_id, 1, NOW(), NOW()),
('Chipatá', '68179', @santander_id, 1, NOW(), NOW()),
('Cimitarra', '68190', @santander_id, 1, NOW(), NOW()),
('Concepción', '68207', @santander_id, 1, NOW(), NOW()),
('Confines', '68209', @santander_id, 1, NOW(), NOW()),
('Contratación', '68211', @santander_id, 1, NOW(), NOW()),
('Coromoro', '68217', @santander_id, 1, NOW(), NOW()),
('Curití', '68229', @santander_id, 1, NOW(), NOW()),
('El Carmen de Chucurí', '68235', @santander_id, 1, NOW(), NOW()),
('El Guacamayo', '68245', @santander_id, 1, NOW(), NOW()),
('El Peñón', '68250', @santander_id, 1, NOW(), NOW()),
('El Playón', '68255', @santander_id, 1, NOW(), NOW()),
('Encino', '68264', @santander_id, 1, NOW(), NOW()),
('Enciso', '68266', @santander_id, 1, NOW(), NOW()),
('Florián', '68271', @santander_id, 1, NOW(), NOW()),
('Floridablanca', '68276', @santander_id, 1, NOW(), NOW()),
('Galán', '68296', @santander_id, 1, NOW(), NOW()),
('Gámbita', '68298', @santander_id, 1, NOW(), NOW()),
('Girón', '68307', @santander_id, 1, NOW(), NOW()),
('Guaca', '68318', @santander_id, 1, NOW(), NOW()),
('Guadalupe', '68320', @santander_id, 1, NOW(), NOW()),
('Guapotá', '68322', @santander_id, 1, NOW(), NOW()),
('Guavatá', '68324', @santander_id, 1, NOW(), NOW()),
('Güepsa', '68327', @santander_id, 1, NOW(), NOW()),
('Hato', '68344', @santander_id, 1, NOW(), NOW()),
('Jesús María', '68368', @santander_id, 1, NOW(), NOW()),
('Jordán', '68370', @santander_id, 1, NOW(), NOW()),
('La Belleza', '68377', @santander_id, 1, NOW(), NOW()),
('La Paz', '68385', @santander_id, 1, NOW(), NOW()),
('Landázuri', '68397', @santander_id, 1, NOW(), NOW()),
('Lebríja', '68406', @santander_id, 1, NOW(), NOW()),
('Los Santos', '68418', @santander_id, 1, NOW(), NOW()),
('Macaravita', '68425', @santander_id, 1, NOW(), NOW()),
('Matanza', '68432', @santander_id, 1, NOW(), NOW()),
('Mogotes', '68444', @santander_id, 1, NOW(), NOW()),
('Molagavita', '68464', @santander_id, 1, NOW(), NOW()),
('Ocamonte', '68468', @santander_id, 1, NOW(), NOW()),
('Oiba', '68470', @santander_id, 1, NOW(), NOW()),
('Onzaga', '68473', @santander_id, 1, NOW(), NOW()),
('Palmar', '68477', @santander_id, 1, NOW(), NOW()),
('Palmas del Socorro', '68479', @santander_id, 1, NOW(), NOW()),
('Páramo', '68495', @santander_id, 1, NOW(), NOW()),
('Pinchote', '68502', @santander_id, 1, NOW(), NOW()),
('Puente Nacional', '68503', @santander_id, 1, NOW(), NOW()),
('Rionegro', '68524', @santander_id, 1, NOW(), NOW()),
('San Andrés', '68547', @santander_id, 1, NOW(), NOW()),
('San Benito', '68549', @santander_id, 1, NOW(), NOW()),
('San Gil', '68572', @santander_id, 1, NOW(), NOW()),
('San Joaquín', '68575', @santander_id, 1, NOW(), NOW()),
('San José de Miranda', '68577', @santander_id, 1, NOW(), NOW()),
('San Miguel', '68580', @santander_id, 1, NOW(), NOW()),
('San Vicente de Chucurí', '68586', @santander_id, 1, NOW(), NOW()),
('Santa Bárbara', '68595', @santander_id, 1, NOW(), NOW()),
('Santa Helena del Opón', '68612', @santander_id, 1, NOW(), NOW()),
('Socorro', '68655', @santander_id, 1, NOW(), NOW()),
('Suaita', '68662', @santander_id, 1, NOW(), NOW()),
('Sucre', '68667', @santander_id, 1, NOW(), NOW()),
('Suratá', '68673', @santander_id, 1, NOW(), NOW()),
('Tona', '68679', @santander_id, 1, NOW(), NOW()),
('Villanueva', '68820', @santander_id, 1, NOW(), NOW()),
('Vélez', '68824', @santander_id, 1, NOW(), NOW()),
('Palmar', '68867', @santander_id, 1, NOW(), NOW());

-- Insertar municipios de Norte de Santander
INSERT INTO municipios (municipioNombre, municipioCodigo, departamentoId, municipioEstado, fechaCreacion, fechaActualizacion) VALUES
('Cúcuta', '54001', @norte_santander_id, 1, NOW(), NOW()),
('Abrego', '54003', @norte_santander_id, 1, NOW(), NOW()),
('Arboledas', '54051', @norte_santander_id, 1, NOW(), NOW()),
('Bochalema', '54099', @norte_santander_id, 1, NOW(), NOW()),
('Bucarasica', '54109', @norte_santander_id, 1, NOW(), NOW()),
('Cácota', '54125', @norte_santander_id, 1, NOW(), NOW()),
('Cácota', '54128', @norte_santander_id, 1, NOW(), NOW()),
('Chinácota', '54172', @norte_santander_id, 1, NOW(), NOW()),
('Chitagá', '54174', @norte_santander_id, 1, NOW(), NOW()),
('Convención', '54206', @norte_santander_id, 1, NOW(), NOW()),
('Cucutilla', '54223', @norte_santander_id, 1, NOW(), NOW()),
('Durania', '54239', @norte_santander_id, 1, NOW(), NOW()),
('El Carmen', '54245', @norte_santander_id, 1, NOW(), NOW()),
('El Tarra', '54250', @norte_santander_id, 1, NOW(), NOW()),
('El Zulia', '54261', @norte_santander_id, 1, NOW(), NOW()),
('Gramalote', '54313', @norte_santander_id, 1, NOW(), NOW()),
('Hacarí', '54344', @norte_santander_id, 1, NOW(), NOW()),
('Herrán', '54347', @norte_santander_id, 1, NOW(), NOW()),
('La Esperanza', '54377', @norte_santander_id, 1, NOW(), NOW()),
('La Playa', '54385', @norte_santander_id, 1, NOW(), NOW()),
('Labateca', '54398', @norte_santander_id, 1, NOW(), NOW()),
('Lourdes', '54405', @norte_santander_id, 1, NOW(), NOW()),
('Los Patios', '54418', @norte_santander_id, 1, NOW(), NOW()),
('Mutiscua', '54454', @norte_santander_id, 1, NOW(), NOW()),
('Ocaña', '54480', @norte_santander_id, 1, NOW(), NOW()),
('Pamplona', '54498', @norte_santander_id, 1, NOW(), NOW()),
('Pamplonita', '54520', @norte_santander_id, 1, NOW(), NOW()),
('Puerto Santander', '54553', @norte_santander_id, 1, NOW(), NOW()),
('Ragonvalia', '54599', @norte_santander_id, 1, NOW(), NOW()),
('Salazar', '54660', @norte_santander_id, 1, NOW(), NOW()),
('San Calixto', '54670', @norte_santander_id, 1, NOW(), NOW()),
('San Cayetano', '54673', @norte_santander_id, 1, NOW(), NOW()),
('Santiago', '54680', @norte_santander_id, 1, NOW(), NOW()),
('Santo Domingo', '54720', @norte_santander_id, 1, NOW(), NOW()),
('Sardinata', '54743', @norte_santander_id, 1, NOW(), NOW()),
('Silos', '54772', @norte_santander_id, 1, NOW(), NOW()),
('Teorama', '54810', @norte_santander_id, 1, NOW(), NOW()),
('Tibú', '54820', @norte_santander_id, 1, NOW(), NOW()),
('Toledo', '54837', @norte_santander_id, 1, NOW(), NOW()),
('Villa Caro', '54854', @norte_santander_id, 1, NOW(), NOW()),
('Villa del Rosario', '54871', @norte_santander_id, 1, NOW(), NOW());

